name: Retrain and (Optionally) Redeploy RCT Model

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-southeast-2
  PIPELINE_ENTRY: pipeline/rct_pipeline.py
  PYTHON_VERSION: "3.11"

jobs:
  retrain-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          
          role-to-assume: arn:aws:iam::383868855578:role/GitHubActionsOIDC-SageMaker
          aws-region: ${{ env.AWS_REGION }}

      - name: Who am I? (sanity)
        run: aws sts get-caller-identity

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          check-latest: true

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-${{ env.PYTHON_VERSION }}-

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install "sagemaker<3" boto3 pandas numpy
          fi

      - name: Sanity check Python
        run: python -c "import sys; import boto3; print('Python OK:', sys.version); print('boto3:', boto3.__version__)"

      - name: Run SageMaker Pipeline
        run: python "$PIPELINE_ENTRY"
